openapi: 3.0.3
info:
  title: Appointment Service API
  version: 1.0.0
paths:
  /appointments:
    get:
      summary: List all appointments
      responses:
        '200':
          description: List of appointments
    post:
      summary: Create a new appointment
      responses:
        '201':
          description: Created
  /appointments/{id}:
    get:
      summary: Get appointment by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Appointment found
        '404':
          description: Not found
    put:
      summary: Update appointment
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete appointment
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
