version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spa
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/docker/postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Example backend service (repeat for each service as needed)
  customer-service:
    build:
      context: ./backend/services/customer-service
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_DSN: postgres://postgres:postgres@postgres:5432/spa?sslmode=disable
      REDIS_ADDR: redis:6379
      # Add other environment variables as needed
    volumes:
      - ./backend/services/customer-service:/app
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["air"] # Hot reloading for Go

  # Example frontend app (repeat for each app as needed)
  customer-app:
    build:
      context: ./frontend/customer-app
      dockerfile: Dockerfile.dev
    environment:
      VITE_API_URL: http://localhost:8080
    volumes:
      - ./frontend/customer-app:/app
    ports:
      - "3001:3000"
    command: ["npm", "run", "dev"] # Hot reloading for Vite

networks:
  default:
    driver: bridge
