apiVersion: v1
kind: Secret
metadata:
  name: spa-secrets
  namespace: spa-system
type: Opaque
data:
  POSTGRES_USER: c3BhX2FkbWlu  # base64: spa_admin
  POSTGRES_PASSWORD: c3BhX3Bhc3N3b3Jk  # base64: spa_password
  POSTGRES_DSN: aG9zdD1kYXRhYmFzZSB1c2VyPXNwYV9hZG1pbiBwYXNzd29yZD1zcGFfcGFzc3dvcmQgZGJuYW1lPXNwYV9kYiBwb3J0PTU0MzIgc3NsbW9kZT1kaXNhYmxlIFRpbWVab25lPUFzaWEvQmFuZ2tvaw==  # base64 of DSN
