apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: spa-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: appointment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: spa-secrets
                  key: POSTGRES_DSN
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: spa-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: spa-config
                  key: REDIS_PORT
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: spa-config
                  key: TZ
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: spa-system
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: appointment-service
