openapi: 3.0.3
info:
  title: Branch Service API
  version: 1.0.0
paths:
  /branches:
    get:
      summary: List all branches
      responses:
        '200':
          description: List of branches
    post:
      summary: Create a new branch
      responses:
        '201':
          description: Created
  /branches/{id}:
    get:
      summary: Get branch by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Branch found
        '404':
          description: Not found
    put:
      summary: Update branch
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete branch
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
