openapi: 3.0.3
info:
  title: Customer Service API
  version: 1.0.0
paths:
  /customers:
    get:
      summary: List all customers
      responses:
        '200':
          description: List of customers
    post:
      summary: Create a new customer
      responses:
        '201':
          description: Created
  /customers/{id}:
    get:
      summary: Get customer by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Customer found
        '404':
          description: Not found
    put:
      summary: Update customer
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete customer
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
