apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-app
  namespace: spa-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staff-app
  template:
    metadata:
      labels:
        app: staff-app
    spec:
      containers:
        - name: staff-app
          image: staff-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: staff-app
  namespace: spa-system
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: staff-app
