openapi: 3.0.3
info:
  title: Staff Service API
  version: 1.0.0
paths:
  /staff:
    get:
      summary: List all staff
      responses:
        '200':
          description: List of staff
    post:
      summary: Create a new staff member
      responses:
        '201':
          description: Created
  /staff/{id}:
    get:
      summary: Get staff by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Staff found
        '404':
          description: Not found
    put:
      summary: Update staff
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete staff
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
